/*
 * @Author: ChenYu ycyplus@gmail.com
 * @Date: 2026-10-08
 * @Description: 权限治理演示数据，仅由 API 适配器管理
 * Copyright (c) 2026 by CHENY, All Rights Reserved 😎.
 */
import type {
  DataPermissionRule,
  TempAuthorization,
  PermissionConstraint,
  AuditLogItem,
} from './permission-governance.contract'

export const MOCK_DATA_PERMISSIONS: DataPermissionRule[] = [
  {
    id: 'dp_1',
    module: 'user',
    moduleName: '用户管理',
    scope: 'all',
    departmentIds: [],
    fieldPermissions: [
      {
        field: 'username',
        label: '用户名',
        visible: true,
        editable: true,
        masked: false,
      },
      {
        field: 'email',
        label: '邮箱',
        visible: true,
        editable: true,
        masked: false,
      },
      {
        field: 'phone',
        label: '手机号',
        visible: true,
        editable: true,
        masked: true,
      },
      {
        field: 'idCard',
        label: '身份证',
        visible: true,
        editable: false,
        masked: true,
      },
      {
        field: 'salary',
        label: '薪资',
        visible: false,
        editable: false,
        masked: true,
      },
    ],
    createTime: '2024-01-01 10:00:00',
    updateTime: '2024-03-15 14:30:00',
  },
  {
    id: 'dp_2',
    module: 'role',
    moduleName: '角色管理',
    scope: 'department',
    departmentIds: ['dept_1'],
    fieldPermissions: [
      {
        field: 'roleName',
        label: '角色名',
        visible: true,
        editable: true,
        masked: false,
      },
      {
        field: 'roleCode',
        label: '角色编码',
        visible: true,
        editable: false,
        masked: false,
      },
      {
        field: 'permissions',
        label: '权限列表',
        visible: true,
        editable: true,
        masked: false,
      },
    ],
    createTime: '2024-01-02 10:00:00',
    updateTime: '2024-03-10 11:20:00',
  },
  {
    id: 'dp_3',
    module: 'log',
    moduleName: '日志管理',
    scope: 'self',
    departmentIds: [],
    fieldPermissions: [
      {
        field: 'content',
        label: '日志内容',
        visible: true,
        editable: false,
        masked: false,
      },
      {
        field: 'operatorIp',
        label: '操作IP',
        visible: true,
        editable: false,
        masked: true,
      },
    ],
    createTime: '2024-01-03 10:00:00',
    updateTime: '2024-02-20 09:15:00',
  },
  {
    id: 'dp_4',
    module: 'order',
    moduleName: '订单管理',
    scope: 'department_below',
    departmentIds: ['dept_1', 'dept_1_1', 'dept_1_2'],
    fieldPermissions: [
      {
        field: 'orderNo',
        label: '订单号',
        visible: true,
        editable: false,
        masked: false,
      },
      {
        field: 'amount',
        label: '金额',
        visible: true,
        editable: true,
        masked: false,
      },
      {
        field: 'customerPhone',
        label: '客户电话',
        visible: true,
        editable: false,
        masked: true,
      },
    ],
    createTime: '2024-02-01 10:00:00',
    updateTime: '2024-03-12 16:00:00',
  },
  {
    id: 'dp_5',
    module: 'file',
    moduleName: '文件管理',
    scope: 'custom',
    departmentIds: ['dept_1', 'dept_2', 'dept_3'],
    fieldPermissions: [
      {
        field: 'fileName',
        label: '文件名',
        visible: true,
        editable: true,
        masked: false,
      },
      {
        field: 'fileSize',
        label: '文件大小',
        visible: true,
        editable: false,
        masked: false,
      },
      {
        field: 'uploadUser',
        label: '上传者',
        visible: true,
        editable: false,
        masked: false,
      },
    ],
    createTime: '2024-02-15 10:00:00',
    updateTime: '2024-03-08 13:45:00',
  },
]

export const MOCK_TEMP_AUTHORIZATIONS: TempAuthorization[] = [
  {
    id: 'ta_1',
    targetRole: 'role_3',
    targetRoleName: '内容编辑员',
    permissions: ['perm_1_1_1', 'perm_1_1_2'],
    permissionNames: ['新增用户', '编辑用户'],
    reason: '系统迁移期间需要临时用户管理权限',
    grantedBy: 'user_1',
    grantedByName: '超级管理员',
    startTime: '2024-03-01 00:00:00',
    expireTime: '2024-03-31 23:59:59',
    status: 'active',
    remark: '系统迁移专用临时授权',
  },
  {
    id: 'ta_2',
    targetRole: 'role_4',
    targetRoleName: '数据分析师',
    permissions: ['perm_2_1_1'],
    permissionNames: ['发布文章'],
    reason: '季度报告发布需要',
    grantedBy: 'user_2',
    grantedByName: '系统管理员1',
    startTime: '2024-02-01 00:00:00',
    expireTime: '2024-02-28 23:59:59',
    status: 'expired',
    remark: '',
  },
  {
    id: 'ta_3',
    targetRole: 'role_5',
    targetRoleName: '测试角色',
    permissions: ['perm_3_1', 'perm_3_2'],
    permissionNames: ['查看报表', '导出数据'],
    reason: '新功能测试需要',
    grantedBy: 'user_1',
    grantedByName: '超级管理员',
    startTime: '2024-01-15 00:00:00',
    expireTime: '2024-01-20 23:59:59',
    status: 'revoked',
    remark: '测试完成，提前撤销',
  },
]

export const MOCK_CONSTRAINTS: PermissionConstraint[] = [
  {
    id: 'con_1',
    type: 'mutual_exclusion',
    sourceId: 'perm_1_1_1',
    sourceName: '新增用户',
    sourceCode: 'system:user:add',
    targetId: 'perm_1_1_3',
    targetName: '删除用户',
    targetCode: 'system:user:delete',
    description: '新增用户和删除用户不能同时授予同一角色（职责分离）',
    createTime: '2024-01-10 10:00:00',
  },
  {
    id: 'con_2',
    type: 'mutual_exclusion',
    sourceId: 'perm_1_2_1',
    sourceName: '新增角色',
    sourceCode: 'system:role:add',
    targetId: 'perm_1_2_3',
    targetName: '删除角色',
    targetCode: 'system:role:delete',
    description: '新增角色和删除角色不能同时授予同一角色（职责分离）',
    createTime: '2024-01-10 10:30:00',
  },
  {
    id: 'con_3',
    type: 'inheritance',
    sourceId: 'perm_1',
    sourceName: '系统管理',
    sourceCode: 'system',
    targetId: 'perm_1_1',
    targetName: '用户管理',
    targetCode: 'system:user',
    description: '拥有系统管理权限自动继承用户管理权限',
    createTime: '2024-01-05 09:00:00',
  },
  {
    id: 'con_4',
    type: 'inheritance',
    sourceId: 'perm_1',
    sourceName: '系统管理',
    sourceCode: 'system',
    targetId: 'perm_1_2',
    targetName: '角色管理',
    targetCode: 'system:role',
    description: '拥有系统管理权限自动继承角色管理权限',
    createTime: '2024-01-05 09:00:00',
  },
]

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log_1',
    operatorName: '超级管理员',
    action: 'grant',
    targetType: 'role',
    targetName: '内容编辑员',
    detail:
      '为角色「内容编辑员」授予「新增用户」「编辑用户」临时权限，有效期至 2024-03-31',
    timestamp: '2024-03-15 14:30:22',
    ip: '192.168.1.100',
  },
  {
    id: 'log_2',
    operatorName: '系统管理员1',
    action: 'modify',
    targetType: 'permission',
    targetName: '导出数据',
    detail: '修改权限「导出数据」的数据范围：全部数据 → 本部门及下级',
    timestamp: '2024-03-14 11:20:15',
    ip: '192.168.1.101',
  },
  {
    id: 'log_3',
    operatorName: '超级管理员',
    action: 'revoke',
    targetType: 'role',
    targetName: '测试角色',
    detail: '撤销角色「测试角色」的「查看报表」「导出数据」临时权限',
    timestamp: '2024-03-13 09:45:30',
    ip: '192.168.1.100',
  },
  {
    id: 'log_4',
    operatorName: '超级管理员',
    action: 'create',
    targetType: 'permission',
    targetName: '文件上传',
    detail: '创建新权限「文件上传」，类型：按钮权限，模块：文件管理',
    timestamp: '2024-03-12 16:10:45',
    ip: '192.168.1.100',
  },
  {
    id: 'log_5',
    operatorName: '系统管理员2',
    action: 'delete',
    targetType: 'permission',
    targetName: '临时测试权限',
    detail: '删除过期的临时测试权限「临时测试权限」',
    timestamp: '2024-03-11 08:30:00',
    ip: '192.168.1.102',
  },
  {
    id: 'log_6',
    operatorName: '超级管理员',
    action: 'grant',
    targetType: 'user',
    targetName: '分析师1',
    detail: '为用户「分析师1」分配角色「数据分析师」',
    timestamp: '2024-03-10 10:00:00',
    ip: '192.168.1.100',
  },
  {
    id: 'log_7',
    operatorName: '超级管理员',
    action: 'modify',
    targetType: 'role',
    targetName: '系统管理员',
    detail: '修改角色「系统管理员」权限：移除「删除用户」权限',
    timestamp: '2024-03-09 15:20:00',
    ip: '192.168.1.100',
  },
  {
    id: 'log_8',
    operatorName: '系统管理员1',
    action: 'modify',
    targetType: 'menu',
    targetName: '数据统计',
    detail: '修改菜单「数据统计」排序值：3 → 2',
    timestamp: '2024-03-08 11:00:00',
    ip: '192.168.1.101',
  },
]
