/*
 * @Author: ChenYu ycyplus@gmail.com
 * @Date: 2026-10-08
 * @FilePath: \Robot_Admin\src\api\role-manage.mock.ts
 * @Description: 角色演示数据，独立于页面展示配置
 * Copyright (c) 2026 by CHENY, All Rights Reserved 😎.
 */
import type {
  PermissionData,
  RoleData,
  RoleUserData,
  RoleDataScope,
  RoleTempAuth,
} from './role-manage.contract'

// ==================== 模拟数据 ====================
export const MOCK_PERMISSION_DATA: PermissionData[] = [
  {
    id: 'perm_1',
    name: '系统管理',
    code: 'system',
    type: 'menu',
    parentId: null,
    path: '/system',
    icon: 'mdi:cog',
    sort: 1,
    status: 1,
    children: [
      {
        id: 'perm_1_1',
        name: '用户管理',
        code: 'system:user',
        type: 'menu',
        parentId: 'perm_1',
        path: '/system/user',
        icon: 'mdi:account',
        sort: 1,
        status: 1,
        children: [
          {
            id: 'perm_1_1_1',
            name: '新增用户',
            code: 'system:user:add',
            type: 'button',
            parentId: 'perm_1_1',
            icon: 'mdi:plus',
            sort: 1,
            status: 1,
          },
          {
            id: 'perm_1_1_2',
            name: '编辑用户',
            code: 'system:user:edit',
            type: 'button',
            parentId: 'perm_1_1',
            icon: 'mdi:pencil',
            sort: 2,
            status: 1,
          },
          {
            id: 'perm_1_1_3',
            name: '删除用户',
            code: 'system:user:delete',
            type: 'button',
            parentId: 'perm_1_1',
            icon: 'mdi:delete',
            sort: 3,
            status: 1,
          },
        ],
      },
      {
        id: 'perm_1_2',
        name: '角色管理',
        code: 'system:role',
        type: 'menu',
        parentId: 'perm_1',
        path: '/system/role',
        icon: 'mdi:account-key',
        sort: 2,
        status: 1,
        children: [
          {
            id: 'perm_1_2_1',
            name: '新增角色',
            code: 'system:role:add',
            type: 'button',
            parentId: 'perm_1_2',
            icon: 'mdi:plus',
            sort: 1,
            status: 1,
          },
          {
            id: 'perm_1_2_2',
            name: '编辑角色',
            code: 'system:role:edit',
            type: 'button',
            parentId: 'perm_1_2',
            icon: 'mdi:pencil',
            sort: 2,
            status: 1,
          },
          {
            id: 'perm_1_2_3',
            name: '删除角色',
            code: 'system:role:delete',
            type: 'button',
            parentId: 'perm_1_2',
            icon: 'mdi:delete',
            sort: 3,
            status: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'perm_2',
    name: '内容管理',
    code: 'content',
    type: 'menu',
    parentId: null,
    path: '/content',
    icon: 'mdi:file-document',
    sort: 2,
    status: 1,
    children: [
      {
        id: 'perm_2_1',
        name: '文章管理',
        code: 'content:article',
        type: 'menu',
        parentId: 'perm_2',
        path: '/content/article',
        icon: 'mdi:file-document-edit',
        sort: 1,
        status: 1,
        children: [
          {
            id: 'perm_2_1_1',
            name: '发布文章',
            code: 'content:article:publish',
            type: 'button',
            parentId: 'perm_2_1',
            icon: 'mdi:publish',
            sort: 1,
            status: 1,
          },
          {
            id: 'perm_2_1_2',
            name: '编辑文章',
            code: 'content:article:edit',
            type: 'button',
            parentId: 'perm_2_1',
            icon: 'mdi:pencil',
            sort: 2,
            status: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'perm_3',
    name: '数据统计',
    code: 'analytics',
    type: 'menu',
    parentId: null,
    path: '/analytics',
    icon: 'mdi:chart-line',
    sort: 3,
    status: 1,
    children: [
      {
        id: 'perm_3_1',
        name: '查看报表',
        code: 'analytics:report:view',
        type: 'button',
        parentId: 'perm_3',
        icon: 'mdi:eye',
        sort: 1,
        status: 1,
      },
      {
        id: 'perm_3_2',
        name: '导出数据',
        code: 'analytics:data:export',
        type: 'button',
        parentId: 'perm_3',
        icon: 'mdi:download',
        sort: 2,
        status: 1,
      },
    ],
  },
]

export const MOCK_ROLE_DATA: RoleData[] = [
  {
    id: 'role_1',
    name: '超级管理员',
    code: 'super_admin',
    type: 'system',
    status: 1,
    description: '系统超级管理员，拥有所有权限',
    permissionIds: [
      'perm_1',
      'perm_1_1',
      'perm_1_1_1',
      'perm_1_1_2',
      'perm_1_1_3',
      'perm_1_2',
      'perm_1_2_1',
      'perm_1_2_2',
      'perm_1_2_3',
      'perm_2',
      'perm_2_1',
      'perm_2_1_1',
      'perm_2_1_2',
      'perm_3',
      'perm_3_1',
      'perm_3_2',
    ],
    permissionNames: [
      '系统管理',
      '用户管理',
      '新增用户',
      '编辑用户',
      '删除用户',
      '角色管理',
      '新增角色',
      '编辑角色',
      '删除角色',
      '内容管理',
      '文章管理',
      '发布文章',
      '编辑文章',
      '数据统计',
      '查看报表',
      '导出数据',
    ],
    userCount: 1,
    sort: 1,
    createTime: '2024-01-01 09:00:00',
    updateTime: '2024-01-15 14:30:00',
    remark: '系统内置角色，不可删除',
  },
  {
    id: 'role_2',
    name: '系统管理员',
    code: 'admin',
    type: 'system',
    status: 1,
    description: '系统管理员，拥有系统管理权限',
    permissionIds: [
      'perm_1',
      'perm_1_1',
      'perm_1_1_1',
      'perm_1_1_2',
      'perm_1_2',
      'perm_1_2_1',
      'perm_1_2_2',
    ],
    permissionNames: [
      '系统管理',
      '用户管理',
      '新增用户',
      '编辑用户',
      '角色管理',
      '新增角色',
      '编辑角色',
    ],
    userCount: 3,
    sort: 2,
    createTime: '2024-01-02 09:00:00',
    updateTime: '2024-01-10 16:20:00',
    remark: '系统管理员角色',
  },
  {
    id: 'role_3',
    name: '内容编辑员',
    code: 'editor',
    type: 'custom',
    status: 1,
    description: '内容编辑员，负责内容管理',
    permissionIds: ['perm_2', 'perm_2_1', 'perm_2_1_1', 'perm_2_1_2'],
    permissionNames: ['内容管理', '文章管理', '发布文章', '编辑文章'],
    userCount: 8,
    sort: 3,
    createTime: '2024-01-03 09:00:00',
    updateTime: '2024-01-12 11:10:00',
  },
  {
    id: 'role_4',
    name: '数据分析师',
    code: 'analyst',
    type: 'custom',
    status: 1,
    description: '数据分析师，查看统计数据',
    permissionIds: ['perm_3', 'perm_3_1', 'perm_3_2'],
    permissionNames: ['数据统计', '查看报表', '导出数据'],
    userCount: 5,
    sort: 4,
    createTime: '2024-01-04 09:00:00',
    updateTime: '2024-01-08 13:45:00',
  },
  {
    id: 'role_5',
    name: '测试角色',
    code: 'test_role',
    type: 'temp',
    status: 0,
    description: '临时测试角色',
    permissionIds: [],
    permissionNames: [],
    userCount: 0,
    sort: 5,
    createTime: '2024-01-06 09:00:00',
    remark: '测试用角色，已禁用',
  },
]

// 模拟用户数据
export const MOCK_USER_DATA: RoleUserData[] = [
  {
    id: 'user_1',
    username: 'admin',
    nickname: '超级管理员',
    email: 'admin@example.com',
    phone: '13800138000',
    deptName: '技术部',
    status: 1,
    createTime: '2024-01-01 09:00:00',
  },
  {
    id: 'user_2',
    username: 'manager1',
    nickname: '系统管理员1',
    email: 'manager1@example.com',
    phone: '13800138001',
    deptName: '管理部',
    status: 1,
    createTime: '2024-01-02 09:00:00',
  },
  {
    id: 'user_3',
    username: 'manager2',
    nickname: '系统管理员2',
    email: 'manager2@example.com',
    phone: '13800138002',
    deptName: '管理部',
    status: 1,
    createTime: '2024-01-02 10:00:00',
  },
  {
    id: 'user_4',
    username: 'manager3',
    nickname: '系统管理员3',
    email: 'manager3@example.com',
    deptName: '管理部',
    status: 1,
    createTime: '2024-01-02 11:00:00',
  },
  {
    id: 'user_5',
    username: 'editor1',
    nickname: '编辑员1',
    email: 'editor1@example.com',
    deptName: '内容部',
    status: 1,
    createTime: '2024-01-03 09:00:00',
  },
  {
    id: 'user_6',
    username: 'editor2',
    nickname: '编辑员2',
    email: 'editor2@example.com',
    deptName: '内容部',
    status: 1,
    createTime: '2024-01-03 10:00:00',
  },
  {
    id: 'user_7',
    username: 'editor3',
    nickname: '编辑员3',
    email: 'editor3@example.com',
    deptName: '内容部',
    status: 1,
    createTime: '2024-01-03 11:00:00',
  },
  {
    id: 'user_8',
    username: 'editor4',
    nickname: '编辑员4',
    email: 'editor4@example.com',
    deptName: '内容部',
    status: 1,
    createTime: '2024-01-03 12:00:00',
  },
  {
    id: 'user_9',
    username: 'editor5',
    nickname: '编辑员5',
    email: 'editor5@example.com',
    deptName: '内容部',
    status: 1,
    createTime: '2024-01-03 13:00:00',
  },
  {
    id: 'user_10',
    username: 'editor6',
    nickname: '编辑员6',
    email: 'editor6@example.com',
    deptName: '内容部',
    status: 1,
    createTime: '2024-01-03 14:00:00',
  },
  {
    id: 'user_11',
    username: 'editor7',
    nickname: '编辑员7',
    email: 'editor7@example.com',
    deptName: '内容部',
    status: 1,
    createTime: '2024-01-03 15:00:00',
  },
  {
    id: 'user_12',
    username: 'editor8',
    nickname: '编辑员8',
    email: 'editor8@example.com',
    deptName: '内容部',
    status: 1,
    createTime: '2024-01-03 16:00:00',
  },
  {
    id: 'user_13',
    username: 'analyst1',
    nickname: '分析师1',
    email: 'analyst1@example.com',
    deptName: '数据部',
    status: 1,
    createTime: '2024-01-04 09:00:00',
  },
  {
    id: 'user_14',
    username: 'analyst2',
    nickname: '分析师2',
    email: 'analyst2@example.com',
    deptName: '数据部',
    status: 1,
    createTime: '2024-01-04 10:00:00',
  },
  {
    id: 'user_15',
    username: 'analyst3',
    nickname: '分析师3',
    email: 'analyst3@example.com',
    deptName: '数据部',
    status: 1,
    createTime: '2024-01-04 11:00:00',
  },
  {
    id: 'user_16',
    username: 'analyst4',
    nickname: '分析师4',
    email: 'analyst4@example.com',
    deptName: '数据部',
    status: 1,
    createTime: '2024-01-04 12:00:00',
  },
  {
    id: 'user_17',
    username: 'analyst5',
    nickname: '分析师5',
    email: 'analyst5@example.com',
    deptName: '数据部',
    status: 1,
    createTime: '2024-01-04 13:00:00',
  },
]

// ==================== 模拟数据：角色数据权限 ====================
export const MOCK_ROLE_DATA_SCOPES: Record<string, RoleDataScope[]> = {
  role_1: [
    { module: 'user', moduleName: '用户管理', scope: 'all' },
    { module: 'role', moduleName: '角色管理', scope: 'all' },
    { module: 'content', moduleName: '内容管理', scope: 'all' },
    { module: 'analytics', moduleName: '数据统计', scope: 'all' },
  ],
  role_2: [
    { module: 'user', moduleName: '用户管理', scope: 'department_below' },
    { module: 'role', moduleName: '角色管理', scope: 'department' },
    { module: 'content', moduleName: '内容管理', scope: 'department_below' },
    { module: 'analytics', moduleName: '数据统计', scope: 'department' },
  ],
  role_3: [
    { module: 'content', moduleName: '内容管理', scope: 'department' },
    { module: 'analytics', moduleName: '数据统计', scope: 'self' },
  ],
  role_4: [
    { module: 'analytics', moduleName: '数据统计', scope: 'department_below' },
  ],
  role_5: [],
}

// ==================== 模拟数据：临时授权 ====================
export const MOCK_TEMP_AUTHS: RoleTempAuth[] = [
  {
    id: 'ta_1',
    roleId: 'role_3',
    roleName: '内容编辑员',
    targetRoleId: 'role_4',
    targetRoleName: '数据分析师',
    permissions: ['perm_3_1'],
    permissionNames: ['查看报表'],
    reason: '季度报告编写需要查看数据报表',
    startTime: '2024-01-10 09:00:00',
    expireTime: '2024-02-10 09:00:00',
    status: 'active',
    grantedBy: 'admin',
  },
  {
    id: 'ta_2',
    roleId: 'role_4',
    roleName: '数据分析师',
    targetRoleId: 'role_3',
    targetRoleName: '内容编辑员',
    permissions: ['perm_2_1_1'],
    permissionNames: ['发布文章'],
    reason: '数据分析结果需要发布为内部文章',
    startTime: '2024-01-05 09:00:00',
    expireTime: '2024-01-20 09:00:00',
    status: 'expired',
    grantedBy: 'admin',
  },
  {
    id: 'ta_3',
    roleId: 'role_2',
    roleName: '系统管理员',
    targetRoleId: 'role_1',
    targetRoleName: '超级管理员',
    permissions: ['perm_1_1_3', 'perm_1_2_3'],
    permissionNames: ['删除用户', '删除角色'],
    reason: '系统数据清理任务临时授权',
    startTime: '2024-01-08 09:00:00',
    expireTime: '2024-01-09 18:00:00',
    status: 'revoked',
    grantedBy: 'super_admin',
  },
]

/**
 * * @description: 获取角色的临时授权列表
 * ? @param {string} roleId 角色ID
 * ! @return {RoleTempAuth[]} 相关的临时授权列表
 */
export const getRoleTempAuths = (roleId: string): RoleTempAuth[] =>
  MOCK_TEMP_AUTHS.filter(
    auth => auth.roleId === roleId || auth.targetRoleId === roleId
  )
